server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /index.html {
    add_header Cache-Control "no-store";
  }

  location = / {
    add_header Cache-Control "no-store";
    try_files /index.html =404;
  }

  location /bridge/ {
    proxy_pass http://host.docker.internal:9977/;
  }

  location /host/ {
    proxy_pass http://host.docker.internal:9914/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
