server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /index.html {
    add_header Cache-Control "no-store";
  }

  location = / {
    add_header Cache-Control "no-store";
    try_files /index.html =404;
  }

  location /bridge/ {
    proxy_pass http://host.docker.internal:9977/;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_cache off;
  }

  location /host/ {
    proxy_pass http://host.docker.internal:9914/;
  }

  location /ws/ {
    proxy_pass http://broker:9988/ws/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
